In [1]:
import numpy as np

In [4]:
first = [1,2,3]
first = np.array(first)

In [5]:
type(first)

numpy.ndarray

In [6]:
second = [[1,2,3],[4,5,6]]
second = np.array(second)

In [7]:
print(second)

[[1 2 3]
 [4 5 6]]


In [8]:
print(type(second))

<class 'numpy.ndarray'>


In [11]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [21]:
np.linspace(2,10,3)

array([ 2.,  6., 10.])

In [22]:
#Creating identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.random.rand(3,2)

array([[0.21036845, 0.48285186],
       [0.06077912, 0.30065216],
       [0.40519864, 0.15354142]])

In [32]:
#normal distribution
np.random.randn(5)

array([-1.05594438, -0.06845625,  2.17418102, -0.79378789,  0.28853189])

In [37]:
x = np.random.randn(2,3)

In [39]:
np.random.randint(0,101,5)

array([87, 48, 89, 19, 47])

In [41]:
np.random.randint(0,101,10)

array([ 8, 85, 40, 92, 90, 90, 56, 62, 20,  6])

In [43]:
np.random.seed(42)

In [44]:
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [47]:
arr = np.arange(0,24)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [51]:
arr.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [55]:
a = np.random.randint(0,101,10)


In [56]:
a

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [58]:
a.argmax()

5

In [59]:
a.argmin()

7

In [60]:
b = a.reshape(2,5)


In [61]:
b

array([[82, 86, 74, 74, 87],
       [99, 23,  2, 21, 52]])

In [63]:
a.shape

(10,)

In [64]:
b.shape

(2, 5)

In [67]:
#slicing numpy arrays
a1 = np.arange(1,40,2)

In [68]:
a1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [69]:
a1[4:]

array([ 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39])

In [70]:
a1[:] = 0

In [71]:
a1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [72]:
a2 = a1.copy()

In [73]:
a2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [74]:
a2[:] = 75

In [75]:
a2

array([75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75,
       75, 75, 75])

In [76]:
#2-d array
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
arr_2d.shape

(2, 3)

In [78]:
arr_2d[1]

array([4, 5, 6])

In [81]:
arr = np.arange(1,20,2)

In [82]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [85]:
arr.reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [86]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [87]:
arr[arr>4]

array([ 5,  7,  9, 11, 13, 15, 17, 19])

NUMPY **OPERATIONS 

In [88]:
first_arr = np.arange(0,10)

In [90]:
first_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
first_arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [92]:
first_arr-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [93]:
first_arr + first_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [94]:
first_arr * first_arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [95]:
#nan value
first_arr/first_arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [96]:
#sqrt 
np.sqrt(first_arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [98]:
np.sin(first_arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [99]:
np.log(arr)

array([0.        , 1.09861229, 1.60943791, 1.94591015, 2.19722458,
       2.39789527, 2.56494936, 2.7080502 , 2.83321334, 2.94443898])

In [100]:
a = first_arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [101]:
a.sum()

100